project:
  type: book
  output-dir: docs

book:
  title: "Sample"
  author: "Norah Jones"
  date: "1/2/2024"
  chapters:
    - part: Lorem
      chapters:
        - index.qmd
        - intro.qmd
    - part: Ipsum
      chapters:
        - gt.qmd
        - cr.qmd
    - part: Custom
      chapters:
        - custom.qmd

  repo-url: https://github.com/aborruso/sample
  repo-branch: main
  repo-actions: [edit, issue]

format:
  html:
    theme:
      - cosmo
      - styles.scss
