project:
  type: book

book:
  title: "Sample"
  author: "Norah Jones"
  date: "1/2/2024"
  chapters:
    - part: Lorem
      chapters:
        - index.qmd
        - intro.qmd
    - part: Ipsum
      chapters:
        - cr.qmd
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
