project:
  type: book
  output-dir: docs
  resources: "resources/gt_input.csv"
  render:
  - "!note.md"

book:
  title: "Sample"
  author: "Norah Jones"
  date: "1/2/2024"
  chapters:
    - part: Lorem
      chapters:
        - index.qmd
        - intro.qmd
        - text.md
    - part: Ipsum
      chapters:
        - gt.qmd
        - cr.qmd
    - part: Custom
      chapters:
        - custom.qmd

  repo-url: https://github.com/aborruso/sample
  repo-branch: main
  repo-actions: [edit, issue]

website:
  back-to-top-navigation: true

format:
  html:
#    lang: "it-IT"
    theme:
      - cosmo
      - styles.scss

execute:
  daemon: false
  freeze: auto
